# Generated by Django 5.0.1 on 2024-02-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('contact_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_breed', models.CharField(max_length=255)),
                ('documents', models.FileField(blank=True, null=True, upload_to='user_documents/')),
            ],
        ),
    ]
